*==============================================================================
* WTA_education_analysis_repository.do
* Reproduces Tables 1-4 and robustness (ordered logit; R1-3) for the WTA paper.
* Cleaned from the corrected analysis do-file: removed unused/experimental
* variables; renamed the beginning-producer dummy and the two common-sample
* markers to neutral names; added variable labels. No specification, sample
* restriction, transformation, or estimate was changed. Set the data path below.
*==============================================================================
*Create a log file (text file) to record all Stata outputs generated by this script.
capture mkdir logs
capture log close
log using "logs/full_stata_output.txt", text replace


*******************************************************
* 1. Prepare Data
*******************************************************
* read the raw data 
*Note: this script reads the de-identified dataset "analysis_data_deidentified.dta"; set datadir below to its folder.

* Set datadir to the folder holding the de-identified data (analysis_data_deidentified.dta):
local datadir "."
use "`datadir'/analysis_data_deidentified.dta", clear
set more off

*set linesize 255 helps reduce table wrapping in the log.
set linesize 255

capture drop A_num_tickets obs   // unused raw columns (verified not used in any command; obs is not a record ID)

*convert string values into numeric values
destring travel_miles_class A_dollars_accept B_wtp_workshop topic1_before topic1_after topic2_before topic2_after topic3_before topic3_after topic4_before topic4_after overall_after cattle_handling_be cattle_handling_af bull_exam_be bull_exam_af vaccine_be vaccine_af heifer_be heifer_af breeding_be breeding_af testing_be testing_af marketing_be marketing_af, replace


*set work.eval_raw;
drop if travel_miles_class == . 

/*Which type of workshop did they attend?
			1. Beginning Farmers  : small_town
			2. Beginning Ranchers : rural_area*/



/*DBegFarm
if the participant has been farming/ranching for less than 10 years,
they are considered as "beginning growers"*/
gen DBegFarm=0	
replace DBegFarm = 1	if classification == "Been Farming less than 10 years" | classification =="Interested in Farming Someday"| classification =="Been Ranching less than 10 years" | classification =="Interested in Ranching Someday" 					
replace DBegFarm = .  if classification == "." 
									



		/*edu_yrs
			1. high school 				= 12
			2. Associates Degree		= 14
			3. some technical college 	= 14
			4. Bachelor Degree			= 16
			5. Graduate Degree			= 20*/
gen edu_yrs = .
replace edu_yrs = 12 if education == "High School"
replace edu_yrs = 14 if education == "Some Technical College" 
replace edu_yrs = 14 if education == "Associates Degree" 
replace edu_yrs = 16 if education == "Bachelor Degree" 
replace edu_yrs = 20 if education == "Graduate Degree" 
								

/*hschool if education == "High School" */

gen hschool = 0
replace hschool = 1 if education == "High School"
replace hschool = . if education == "."


/*somecollege
if education == "Some Technical College"  or education == "Associates Degree" */

gen somecollege = 0
replace somecollege = 1 if education == "Some Technical College" | education == "Associates Degree" 
replace somecollege = . if education == "."

/*college
if education == "Bachelor Degree" */

gen college=0
replace college = 1 if education == "Bachelor Degree" 
replace college = . if education == "."

/*advdegree
if education ==  "Graduate Degree" */

gen advdegree=0
replace advdegree = 1 if education == "Graduate Degree" 
replace advdegree = . if education == "."

summarize hschool somecollege college advdegree

		/*age_num
			1. < 20 yrs					= 18
			2. 20-24 yrs 				= 22
			3. 25-34 yrs				= 29.5
			4. 35-44 yrs			 	= 39.5
			5. 45-54 yrs				= 49.5
			6. 55-64 yrs				= 59.5
			7. >= 65 yrs				= 70*/
gen age_num = .
replace age_num = 18 if age == "< 20 yrs" 
replace age_num = 22 if age == "20-24 yrs" 
replace age_num = 29.5	if age == "25-34 yrs" 
replace age_num = 39.5	if age == "35-44 yrs" 
replace age_num = 49.5	if age == "45-54 yrs" 
replace age_num = 59.5	if age == "55-64 yrs" 
replace age_num = 70	if age == ">= 65 yrs" 

					 					
/*gender*/
gen d_male = 0
replace d_male = 1 if gender == "Male" 
replace d_male = . if gender == "." 

/*gender*/
gen d_female = 0
replace d_female = 1 if gender == "Female" 
replace d_female = . if gender == "." 

summarize d_male d_female


		/*WTA*/
gen WTA = A_dollars_accept


		/*WTP*/
gen WTP = B_wtp_workshop

/*no_ppl (No. of ppl attend the workshop together, including him/herself)*/
gen no_ppl =.	
replace no_ppl=1 if travel_alone == "self" 
replace no_ppl=2 if travel_alone == "1 other" 
replace no_ppl=3 if travel_alone == "2 other" 
replace no_ppl=4 if inlist(travel_alone, ">=3 other", ">= 3 other", ">=3 others", ">= 3 others")  // BUGFIX 2026-06-24: data store ">= 3 other" (with a space); original matched only ">=3 other" and silently dropped 7 participants from no_ppl and travel cost 
			
replace cost_cover = "By myself" if collect_location == "small_town"
		
gen mileage = travel_miles_class

/* those with costs covered by an organization or employer were taken out of the calulations of travel cost 
and consequently their travel mileage was set to 0 and this was done using the following code:*/
*replace mileage = 0 if cost_cover == "By an organization or employer"		
		/*travel_miles_class*/

/*average travel times (avg_speed)
small_town equation: avg_speed = 23.075*(mileage)^0.176*exp(-0.000*mileage)
rural_area euqtaion: 8.431*(mileage)^0.402*exp(-0.001*mileage)*/
			
gen avg_speed = .
replace avg_speed = 53.356-24.509*0.978^mileage if collect_location == "small_town"
replace avg_speed =	54.104-40.822*0.982^mileage if collect_location == "rural_area"
summarize avg_speed

/* U.S average hourly wage (avg_hour_wage) calculation by education level and gender

Education			Men (2019$)		Women (2019$)	All (2019$)
High School			$20.96			$16.15			$18.91
Some College		$23.58			$18.44			$20.97
college				$39.99			$29.55			$34.63
advanced Degree		$52.38			$38.64			$45.07
Source : State of Working America Wages 2019 https://files.epi.org/pdf/183498.pdf (last accessed 03/07/2023)


U.S median nominal hourly wage (med_hour_wage) calculation by education level and gender
Nominal				2019 	2019	2020	2020	2021	2021
Education			Men		Women	Men		Women	Men		Women
High School			$17.52 	$14.13 	$18.49 	$14.96 	$19.03 	$15.45 
Some College		$19.44 	$15.51 	$20.42 	$16.51 	$20.90 	$17.17 
college				$30.60 	$24.17 	$33.19 	$25.43 	$33.10 	$25.96 
advanced Degree		$41.35 	$31.53 	$43.31 	$33.13 	$44.23 	$33.82 
 

Citation: Economic Policy Institute. 2025. State of Working America Data Library, Version 2025.6.18. https://data.epi.org.
Source download link: https://economic.github.io/data/
*/
gen     med_hour_wage = 17.52 if d_male   == 1 & hschool     == 1  & year     == 2019
replace med_hour_wage = 19.44 if d_male   == 1 & somecollege == 1  & year     == 2019
replace med_hour_wage = 30.60 if d_male   == 1 & college     == 1  & year     == 2019
replace med_hour_wage = 41.35 if d_male   == 1 & advdegree   == 1  & year     == 2019
replace med_hour_wage = 14.13 if d_female == 1 & hschool     == 1  & year     == 2019
replace med_hour_wage = 15.51 if d_female == 1 & somecollege == 1  & year     == 2019
replace med_hour_wage = 24.17 if d_female == 1 & college     == 1  & year     == 2019
replace med_hour_wage = 31.53 if d_female == 1 & advdegree   == 1  & year     == 2019

  *2020

replace med_hour_wage = 18.49 if d_male   == 1 & hschool     == 1  & year     == 2020
replace med_hour_wage = 20.42 if d_male   == 1 & somecollege == 1  & year     == 2020
replace med_hour_wage = 33.19 if d_male   == 1 & college     == 1  & year     == 2020
replace med_hour_wage = 43.31 if d_male   == 1 & advdegree   == 1  & year     == 2020
replace med_hour_wage = 14.96 if d_female == 1 & hschool     == 1  & year     == 2020
replace med_hour_wage = 16.51 if d_female == 1 & somecollege == 1  & year     == 2020
replace med_hour_wage = 25.43 if d_female == 1 & college     == 1  & year     == 2020
replace med_hour_wage = 33.13 if d_female == 1 & advdegree   == 1  & year     == 2020
 
 *2021
 
replace med_hour_wage = 19.03 if d_male   == 1 & hschool     == 1  & year     == 2021
replace med_hour_wage = 20.90 if d_male   == 1 & somecollege == 1  & year     == 2021
replace med_hour_wage = 33.10 if d_male   == 1 & college     == 1  & year     == 2021
replace med_hour_wage = 44.23 if d_male   == 1 & advdegree   == 1  & year     == 2021
replace med_hour_wage = 15.45 if d_female == 1 & hschool     == 1  & year     == 2021
replace med_hour_wage = 17.17 if d_female == 1 & somecollege == 1  & year     == 2021
replace med_hour_wage = 25.96 if d_female == 1 & college     == 1  & year     == 2021
replace med_hour_wage = 33.82 if d_female == 1 & advdegree   == 1  & year     == 2021

summarize med_hour_wage
tab med_hour_wage	

	
/* Trvale cost
Travelcost = value_traveltime + cost_of_travel*/

/*Using the 2019 (American Automobile  Association) (AAA) statictics we assumed the cost of travel is $0.62 per mile */
gen cost_of_travel 		= ((mileage*2)/no_ppl)*0.62 if year==2019
replace cost_of_travel 	= ((mileage*2)/no_ppl)*0.64 if year==2020
replace cost_of_travel 	= ((mileage*2)/no_ppl)*0.64 if year==2021

replace cost_of_travel = 0 if cost_cover == "By an organization or employer"

/* the value of travel time is assumed to be the value of time travel and the opportunity cost of the time spent at the training site (6 hours).
We then multiplied each of these two times by one-third of the average wage derived above*/
gen traveltime = 2*(mileage/avg_speed)
gen value_traveltime = traveltime*(med_hour_wage/3)

/* opportunity cost of time to attend trainings where 6 represent the total number of hours spent at the training sites*/
gen cost_attendance = 6*(med_hour_wage/3) 
replace cost_attendance = 0 if cost_cover == "By an organization or employer"

summarize traveltime
summarize value_traveltime
summarize cost_attendance
tab traveltime
tab value_traveltime
tab cost_attendance

/* the total value of travel cost (total_tarvelcost) is the summation of cost of travel and the value of travel time*/
gen total_travelcost = cost_of_travel + value_traveltime
replace total_travelcost = 0 if cost_cover == "By an organization or employer"
* 
gen cost_day = total_travelcost + cost_attendance
/* Adjusted WTP by total travel cost (AdjWTPtcost) when only when travel costs not paid by organization or empployee*/

gen AdjWTPtcost = WTP + total_travelcost
replace  AdjWTPtcost = WTP if cost_cover == "By an organization or employer"


/* Adjusted WTP by total travel cost (AdjWTAtcost) when only when travel costs not paid by organization or empployee*/

gen AdjWTAtcost = WTA - total_travelcost
replace  AdjWTAtcost = WTA if cost_cover == "By an organization or employer"


/* Average Knowledge after*/
egen avgknowledge_af = rowmean(topic1_after topic2_after topic3_after topic4_after cattle_handling_af bull_exam_af vaccine_af heifer_af breeding_af testing_af marketing_af)


/* Average Knowledge before*/
egen avgknowledge_be = rowmean(topic1_before topic2_before topic3_before topic4_before cattle_handling_be bull_exam_be vaccine_be heifer_be breeding_be testing_be marketing_be)


		/*Workshop improve the reality*/
gen enhance_success = .
replace enhance_success = 1 if class_improve_reality == "Definitely" 
replace enhance_success = 0 if class_improve_reality == "Probably" | class_improve_reality == "Maybe"


		/*Workshop influence future*/
gen influ_future = .			
replace influ_future = 1 if class_influence_future == "Solidified current commitment to farming" 
replace influ_future = 0 if class_influence_future == "Definitely like to start some day" | class_influence_future == "No change/ Undecided" | class_influence_future == "Convinced me not to farm" 


* Generate difference WTA and WTP
*Generate ratios
gen ratio_WTA_WTP = WTA/WTP
gen ratio_adj_WTA_WTP =  AdjWTAtcost/AdjWTPtcost

* Generate log values
gen WTP_log = log(WTP)


* ---- Variable labels: paper-facing table tokens (submitted-manuscript wording) ----
label variable WTA "WTA"
label variable WTP "WTP"
label variable WTP_log "Ln(WTP)"
label variable no_ppl "Npeople"
label variable mileage "Nmiles"
label variable total_travelcost "TravC"
label variable cost_attendance "OPCattend"
label variable cost_day "TotC"
label variable AdjWTAtcost "WTA - TravC"
label variable AdjWTPtcost "WTP + TravC"
label variable DBegFarm "DBegFarm"
label variable avgknowledge_be "AvgKnowBef"
label variable avgknowledge_af "AvgKnowAft"
label variable edu_yrs "Education"
label variable d_male "Male"
label variable age_num "Age"

/*=============================================================================================================================================================================

					Descriptive Statistics

=============================================================================================================================================================================*/
*Standard Descriptive statistics Table
summarize no_ppl mileage cost_day cost_attendance DBegFarm edu_yrs age_num d_male WTA WTP WTP_log AdjWTAtcost AdjWTPtcost ratio_WTA_WTP ratio_adj_WTA_WTP enhance_success influ_future avgknowledge_be

* Descriptive statistics for only mean, mdedian and N

tabstat WTA WTP no_ppl mileage total_travelcost cost_attendance cost_day AdjWTAtcost AdjWTPtcost DBegFarm avgknowledge_be avgknowledge_af edu_yrs, stats(mean median n)

tabstat WTA WTP no_ppl mileage cost_day cost_attendance total_travelcost AdjWTAtcost WTP AdjWTPtcost DBegFarm avgknowledge_be hschool, stats(mean median n)


*Standard Descriptive statistics Table
summarize WTA WTP no_ppl mileage total_travelcost cost_attendance cost_day AdjWTAtcost WTP AdjWTPtcost DBegFarm avgknowledge_be avgknowledge_af edu_yrs d_male age_num

* Few Selected Descriptive statistics for only mean, mdedian and N

tabstat WTA WTP no_ppl mileage total_travelcost cost_attendance cost_day AdjWTAtcost WTP AdjWTPtcost DBegFarm avgknowledge_be avgknowledge_af edu_yrs d_male age_num, stats(mean median n)

/*=============================================================================================================================================================================*/ 
/*  Table 1 Model With constant  */

regress WTA WTP, robust
eststo model1_1r
outreg2 using "First_table_Linear_WTA_3rd_Wage.doc", replace ctitle(WTA)
predict model1_1r_resid, resid
swilk model1_1r_resid  // Tests normality of OLS residuals

regress WTA WTP_log, robust
eststo model1_2r
outreg2 using "First_table_Linear_WTA_3rd_Wage.doc", append ctitle(WTA)
predict model1_2r_resid, resid
swilk model1_2r_resid  // Tests normality of OLS residuals

regress WTA WTP_log total_travelcost, robust
eststo model1_3r
outreg2 using "First_table_Linear_WTA_3rd_Wage.doc", append ctitle(WTA)
predict model1_3r_resid, resid
swilk model1_3r_resid  // Tests normality of OLS residuals

regress WTA WTP_log cost_day, robust
eststo model1_4r
outreg2 using "First_table_Linear_WTA_3rd_Wage.doc", append ctitle(WTA)
predict model1_4r_resid, resid
swilk model1_4r_resid  // Tests normality of OLS residuals

xi: regress WTA WTP_log DBegFarm avgknowledge_be avgknowledge_af, robust
eststo model1_5r
outreg2 using "First_table_Linear_WTA_3rd_Wage.doc", append ctitle(WTA)
predict model1_5r_resid, resid
swilk model1_5r_resid  // Tests normality of OLS residuals

esttab model1_1r model1_2r model1_3r model1_4r model1_5r , r2 ar2 se scalar("ll Log lik." "rmse") aic bic label	
/*=============================================================================================================================================================================*/ 

/*  Table 1 Model With constant  */

regress WTA WTP_log avgknowledge_be avgknowledge_af total_travelcost, robust
gen common_sample_ols = e(sample)

regress WTA WTP if common_sample_ols, robust
eststo model1_1rs
outreg2 using "Sample_table_Linear_WTA_3rd_Wage.doc", replace ctitle(WTA)
predict model1_1r_resid_sam, resid
swilk model1_1r_resid_sam  // Tests normality of OLS residuals

regress WTA WTP_log if common_sample_ols, robust
eststo model1_2rs
outreg2 using "Sample_table_Linear_WTA_3rd_Wage.doc", append ctitle(WTA)
predict model1_2r_resid_sam, resid
swilk model1_2r_resid_sam  // Tests normality of OLS residuals

regress WTA WTP_log total_travelcost if common_sample_ols, robust
eststo model1_3rs
outreg2 using "Sample_table_Linear_WTA_3rd_Wage.doc", append ctitle(WTA)
predict model1_3r_resid_sam, resid
swilk model1_3r_resid_sam  // Tests normality of OLS residuals

regress WTA WTP_log cost_day if common_sample_ols, robust
eststo model1_4rs
outreg2 using "Sample_table_Linear_WTA_3rd_Wage.doc", append ctitle(WTA)
predict model1_4r_resid_sam, resid
swilk model1_4r_resid_sam  // Tests normality of OLS residuals

xi: regress WTA WTP_log DBegFarm avgknowledge_be avgknowledge_af if common_sample_ols, robust
eststo model1_5rs
outreg2 using "Sample_table_Linear_WTA_3rd_Wage.doc", append ctitle(WTA)
predict model1_5r_resid_sam, resid
swilk model1_5r_resid_sam  // Tests normality of OLS residuals

esttab model1_1rs model1_2rs model1_3rs model1_4rs model1_5rs , r2 ar2 se scalar("ll Log lik." "rmse") aic bic label	
/*=============================================================================================================================================================================*/ 


* Subset to keep consistent sample for all models

*******************************************************
* 2. Define model specifications
*******************************************************
local model1 "WTA WTP_log"
local model2 "WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af"
local model3 "WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost "
local model4 "WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af edu_yrs i.d_male age_num"
local model5 "WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost edu_yrs i.d_male age_num"

*******************************************************
* 3. OLS regressions (Linear models)
*******************************************************
* Model 1: OLS
regress `model1', robust
eststo lin_m1
outreg2 using "Linear_Full_WTA_3rd_Wage_combined.doc", replace ctitle(WTA)
* Store Adjusted R^2, then generate residuals and test normality
estadd scalar adj_r2 = e(r2_a)
predict lin_m1_resid, resid
swilk lin_m1_resid  // Tests normality of OLS residuals


* Model 2: OLS
regress `model2', robust
eststo lin_m2
outreg2 using "Linear_Full_WTA_3rd_Wage_combined.doc", append ctitle(WTA)

estadd scalar adj_r2 = e(r2_a)
predict lin_m2_resid, resid
swilk lin_m2_resid

* Model 3: OLS
regress `model3', robust
eststo lin_m3
outreg2 using "Linear_Full_WTA_3rd_Wage_combined.doc", append ctitle(WTA)

estadd scalar adj_r2 = e(r2_a)
predict lin_m3_resid, resid
swilk lin_m3_resid

* Model 4: OLS
regress `model4', robust
eststo lin_m4
outreg2 using "Linear_Full_WTA_3rd_Wage_combined.doc", append ctitle(WTA)

estadd scalar adj_r2 = e(r2_a)
predict lin_m4_resid, resid
swilk lin_m4_resid

* Model 5: OLS
regress `model5', robust
eststo lin_m5
outreg2 using "Linear_Full_WTA_3rd_Wage_combined.doc", append ctitle(WTA)

estadd scalar adj_r2 = e(r2_a)
predict lin_m5_resid, resid
swilk lin_m5_resid


esttab lin_m1 lin_m2 lin_m3 lin_m4 lin_m5, stats(adj_r2 aic bic ll) label
        
*******************************************************
* 4. Ordered Probit regressions
*******************************************************
* Model 1: Ordered Probit
oprobit `model1', robust
eststo oprobit_m1
outreg2 using "Oprobit_FullModel_WTA_3rd_Wage.doc", replace ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m1_xb, xb
swilk oprobit_m1_xb  // Not a residual normality test, just distribution of linear predictor

* Model 2
oprobit `model2', robust
eststo oprobit_m2
outreg2 using "Oprobit_FullModel_WTA_3rd_Wage.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m2_xb, xb
swilk oprobit_m2_xb

* Model 3
oprobit `model3', robust
eststo oprobit_m3
outreg2 using "Oprobit_FullModel_WTA_3rd_Wage.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m3_xb, xb
swilk oprobit_m3_xb

* Model 4
oprobit `model4', robust
eststo oprobit_m4
outreg2 using "Oprobit_FullModel_WTA_3rd_Wage.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m4_xb, xb
swilk oprobit_m4_xb

* Model 5
oprobit `model5', robust
eststo oprobit_m5
outreg2 using "Oprobit_FullModel_WTA_3rd_Wage.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m5_xb, xb
swilk oprobit_m5_xb

esttab oprobit_m1 oprobit_m2 oprobit_m3 oprobit_m4 oprobit_m5, stats(pR2 aic bic ll) label

 


*******************************************************
* 4.b. Ordered Probit regressions using the same sample accross all models
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost edu_yrs i.d_male age_num, robust
gen common_sample_oprobit = e(sample)

* Model 1: Ordered Probit
oprobit `model1' if common_sample_oprobit, robust
eststo oprobit_m1s
outreg2 using "Sample_Oprobit_FullModel_WTA.doc", replace ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m1s_xb, xb
swilk oprobit_m1s_xb  // Not a residual normality test, just distribution of linear predictor

* Model 2
oprobit `model2' if common_sample_oprobit, robust
eststo oprobit_m2s
outreg2 using "Sample_Oprobit_FullModel_WTA.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m2s_xb, xb
swilk oprobit_m2s_xb

* Model 3
oprobit `model3' if common_sample_oprobit, robust
eststo oprobit_m3s
outreg2 using "Sample_Oprobit_FullModel_WTA.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m3s_xb, xb
swilk oprobit_m3s_xb

* Model 4
oprobit `model4' if common_sample_oprobit, robust
eststo oprobit_m4s
outreg2 using "Sample_Oprobit_FullModel_WTA.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m4s_xb, xb
swilk oprobit_m4s_xb

* Model 5
oprobit `model5' if common_sample_oprobit, robust
eststo oprobit_m5s
outreg2 using "Sample_Oprobit_FullModel_WTA.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict oprobit_m5s_xb, xb
swilk oprobit_m5s_xb

esttab oprobit_m1s oprobit_m2s oprobit_m3s oprobit_m4s oprobit_m5s, stats(pR2 aic bic ll) label


*******************************************************
* 5. Ordered Logit regressions
*******************************************************
* Model 1: Ordered Logit
ologit `model1', robust
eststo ologit_m1
outreg2 using "Ologit_FullModel_WTA_3rd_Wage.doc", replace ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict ologit_m1_xb, xb
swilk ologit_m1_xb  // Again, distribution check for xb

* Model 2
ologit `model2', robust
eststo ologit_m2
outreg2 using "Ologit_FullModel_WTA_3rd_Wage.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict ologit_m2_xb, xb
swilk ologit_m2_xb

* Model 3
ologit `model3', robust
eststo ologit_m3
outreg2 using "Ologit_FullModel_WTA_3rd_Wage.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict ologit_m3_xb, xb
swilk ologit_m3_xb

* Model 4
ologit `model4', robust
eststo ologit_m4
outreg2 using "Ologit_FullModel_WTA_3rd_Wage.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict ologit_m4_xb, xb
swilk ologit_m4_xb


* Model 5
ologit `model5', robust
eststo ologit_m5
outreg2 using "Ologit_FullModel_WTA_3rd_Wage.doc", append ctitle(WTA)

estadd scalar pR2 = e(r2_p)
predict ologit_m5_xb, xb
swilk ologit_m5_xb


esttab ologit_m1 ologit_m2 ologit_m3 ologit_m4 ologit_m5, stats(pR2 aic bic ll) label

*******************************************************
*  Marginal Effects for each model
*     - all in the same .doc, side-by-side
*******************************************************
* We will create a second file "Oprobit_MarginalEffects_WTP_log.doc"
* that has columns (1)-(4) for MEs of WTP_log from the same four models.

*******************************************************
* Model 1
*******************************************************
oprobit WTA WTP_log, robust
margins, dydx(WTP_log) atmeans post
eststo ME_model1
outreg2 ME_model1 using "MarginalEffects_WTP_log.doc", replace ///
    ctitle(" (3.1), Ln(WTP)") drop(/cut*)


*******************************************************
* Model 2
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af, robust
margins, dydx(WTP_log) atmeans post
eststo ME_model3
outreg2 ME_model3 using "MarginalEffects_WTP_log.doc", append ///
    ctitle("(3.2), Ln(WTP)") drop(/cut*)

*******************************************************
* Model 3
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost, robust
margins, dydx(WTP_log) atmeans post
eststo ME_model3
outreg2 ME_model3 using "MarginalEffects_WTP_log.doc", append ///
    ctitle("(3.3), Ln(WTP)") drop(/cut*)


	*******************************************************
* Model 4
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af edu_yrs i.d_male age_num, robust
margins, dydx(WTP_log) atmeans post
eststo ME_model4
outreg2 ME_model4 using "MarginalEffects_WTP_log.doc", append ///
    ctitle("(3.4), Ln(WTP)") drop(/cut*)
	
*******************************************************
* Model 5
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost edu_yrs i.d_male age_num, robust
margins, dydx(WTP_log) atmeans post
eststo ME_model5
outreg2 ME_model5 using "MarginalEffects_WTP_log.doc", append ///
    ctitle("Model 5, Ln(WTP)") drop(/cut*)
	


* We will create a second file "Oprobit_MarginalEffects_d_begin_growers.doc"
* that has columns (1)-(4) for MEs of avgknowledge_be from the same four models.



*******************************************************
* Model 2
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af, robust
margins, dydx(DBegFarm) atmeans post
eststo ME_model2
outreg2 ME_model2 using "MarginalEffects_d_begin_growers.doc", replace ///
    ctitle("(3.2), DBegFarm") drop(/cut*)

*******************************************************
* Model 3
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost, robust
margins, dydx(DBegFarm) atmeans post
eststo ME_model3
outreg2 ME_model3 using "MarginalEffects_d_begin_growers.doc", append ///
    ctitle("(3.3), DBegFarm") drop(/cut*)	

*******************************************************
* Model 4
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af edu_yrs i.d_male age_num, robust
margins, dydx(DBegFarm) atmeans post
eststo ME_model4
outreg2 ME_model4 using "MarginalEffects_d_begin_growers.doc", append ///
    ctitle("(3.4), DBegFarm") drop(/cut*)

*******************************************************
* Model 5
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost edu_yrs i.d_male age_num, robust
margins, dydx(DBegFarm) atmeans post
eststo ME_model5
outreg2 ME_model5 using "MarginalEffects_d_begin_growers.doc", append ///
    ctitle("(3.5), DBegFarm") drop(/cut*)
	




*******************************************************	
*******************************************************
* We will create a second file "Oprobit_MarginalEffects_avgknowledge_be.doc"
* that has columns (1)-(4) for MEs of avgknowledge_be from the same four models.


*******************************************************
* Model 2
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af, robust
margins, dydx(avgknowledge_be) atmeans post
eststo ME_model2
outreg2 ME_model2 using "MarginalEffects_avgknowledge_be.doc", replace ///
    ctitle("(3.2), AvgKnowBef") drop(/cut*)

*******************************************************
* Model 3
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost, robust
margins, dydx(avgknowledge_be) atmeans post
eststo ME_model3
outreg2 ME_model3 using "MarginalEffects_avgknowledge_be.doc", append ///
    ctitle("(3.3), AvgKnowBef") drop(/cut*)	
	
*******************************************************
* Model 4
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af edu_yrs i.d_male age_num, robust
margins, dydx(avgknowledge_be) atmeans post
eststo ME_model4
outreg2 ME_model4 using "MarginalEffects_avgknowledge_be.doc", append ///
    ctitle("(3.4), AvgKnowBef") drop(/cut*)
	
*******************************************************
* Model 5
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost edu_yrs i.d_male age_num, robust
margins, dydx(avgknowledge_be) atmeans post
eststo ME_model5
outreg2 ME_model5 using "MarginalEffects_avgknowledge_be.doc", append ///
    ctitle("(3.5), AvgKnowBef") drop(/cut*)


*******************************************************
* We will create a second file "Oprobit_MarginalEffects_avgknowledge_af.doc"
* that has columns (1)-(4) for MEs of avgknowledge_af from the same four models.


*******************************************************
* Model 2
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af, robust
margins, dydx(avgknowledge_af) atmeans post
eststo ME_model2
outreg2 ME_model2 using "MarginalEffects_avgknowledge_af.doc", replace ///
    ctitle("(3.2), AvgKnowAft") drop(/cut*)

*******************************************************
* Model 3
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost, robust
margins, dydx(avgknowledge_af) atmeans post
eststo ME_model3
outreg2 ME_model3 using "MarginalEffects_avgknowledge_af.doc", append ///
    ctitle("(3.3), AvgKnowAft") drop(/cut*)		

*******************************************************
* Model 4
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af edu_yrs i.d_male age_num, robust
margins, dydx(avgknowledge_af) atmeans post
eststo ME_model4
outreg2 ME_model4 using "MarginalEffects_avgknowledge_af.doc", append ///
    ctitle("(3.4), AvgKnowAft") drop(/cut*)
	
*******************************************************
* Model 4
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost edu_yrs i.d_male age_num, robust
margins, dydx(avgknowledge_af) atmeans post
eststo ME_model5
outreg2 ME_model5 using "MarginalEffects_avgknowledge_af.doc", append ///
    ctitle("(3.5), AvgKnowAft") drop(/cut*)	
	
	
***********************************************************************************************************************
******************** ************ try with Travel cost ****************************************************************
***********************************************************************************************************************	
	
* We will create a second file "Oprobit_MarginalEffects_total_travelcost.doc"
* that has columns (3)and(5) for MEs of total_travelcost at the same WTA levels for the two models.


*******************************************************
* Model 3
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost, robust
margins, dydx(total_travelcost) atmeans post
eststo ME_model3 
outreg2 ME_model3 using "MarginalEffects_total_travelcost.doc", replace ///
    ctitle("(3.3), TravC") drop(/cut*)	

*******************************************************
* Model 5
*******************************************************
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af total_travelcost edu_yrs i.d_male age_num , robust
margins, dydx(total_travelcost) atmeans post
eststo ME_model5
outreg2 ME_model5 using "MarginalEffects_total_travelcost.doc", append ///
    ctitle("(3.5), TravC") drop(/cut*)
	

	
*=============================================================================
* R1-3 ROBUSTNESS CHECK (Reviewer #1 omitted-factors comment)
*
* Adds the two collected-but-omitted PERCEIVED-BENEFIT / EFFICACY items to the
* full WTA model (Model 5):
*     enhance_success  (1 = class "Definitely" improves reality; 0 = Probably/Maybe)
*     influ_future     (1 = "Solidified current commitment"; 0 = other responses)
*
* TRUST / INSTITUTIONAL-CONFIDENCE and RISK / BEHAVIORAL measures were NOT
* collected in the instrument, so they are addressed as a LIMITATION, not added.
*
* Paste this block at the END of:
*   2025.07.08_Update_avgknowledge_NullTravelCost_WTA_3rdWage.do
* (after the section that generates enhance_success and influ_future).
* This produces the OFFICIAL numbers; a Python pre-check indicated results are
* stable and the two items are individually insignificant, but confirm here.
*=============================================================================

* Common sample = obs with both new items non-missing (keeps base vs aug comparable)
gen byte rob_samp = !missing(enhance_success, influ_future)

*---------------------------------------------------------------- OLS
regress WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af ///
        total_travelcost edu_yrs i.d_male age_num if rob_samp, robust
eststo rob_ols_base

regress WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af ///
        total_travelcost edu_yrs i.d_male age_num enhance_success influ_future, robust
eststo rob_ols_aug

*---------------------------------------------------------- Ordered probit
oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af ///
        total_travelcost edu_yrs i.d_male age_num if rob_samp, robust
eststo rob_op_base

oprobit WTA WTP_log i.DBegFarm avgknowledge_be avgknowledge_af ///
        total_travelcost edu_yrs i.d_male age_num enhance_success influ_future, robust
eststo rob_op_aug

esttab rob_ols_base rob_ols_aug rob_op_base rob_op_aug, ///
        se r2 ar2 aic bic label nogaps ///
        title("R1-3 robustness: perceived-benefit items added to Model 5")

* Export a formatted table. esttab handles multiple stored estimates cleanly;
* the previous outreg2 ctitle("a","b",...) LIST caused r(198) "invalid name"
* and aborted the do-file before the diagnostics below could run.
esttab rob_ols_base rob_ols_aug rob_op_base rob_op_aug using ///
        "R1_3_robustness_perceived_benefit.rtf", replace se r2 ar2 aic bic label nogaps ///
        mtitles("OLS base" "OLS +items" "OProbit base" "OProbit +items") ///
        title("R1-3 robustness: perceived-benefit items added to Model 5")

*------------------------------------------------ Diagnostics requested in review
* Collinearity with the before/after knowledge variables
regress WTA WTP_log avgknowledge_be avgknowledge_af total_travelcost ///
        edu_yrs age_num enhance_success influ_future if rob_samp
estat vif
pwcorr avgknowledge_be avgknowledge_af enhance_success influ_future, sig

* Sample sizes / coverage
count if rob_samp
tab enhance_success, missing
tab influ_future, missing
	

* Use the following to close the log file created. Always put at the end
log close
